-- menu_hotkeys_localization.lua

local mod = get_mod("menu_hotkeys")

local localizations = {
	mod_name = {
		en = "Menu Hotkeys",
		ru = "Горячие клавиши меню",
 ["zh-cn"] = "菜单快捷键",
 ["zh-tw"] = "選單快捷鍵",
		de = "Menü-Hotkeys",
		fr = "Raccourcis des menus",
		ja = "メニューホットキー",
		ko = "메뉴 단축키",
		it = "Tasti rapidi dei menu",
		pl = "Skróty klawiszowe menu",
		es = "Teclas rápidas de menú",
 ["pt-br"] = "Atalhos do menu",
	},
	mod_description = {
		en = "Open various menus from the Hub, Psykhanium and Solo Play with hotkeys.",
		ru = "Menu Hotkeys - С разрешения товарища dalokraff я выкладываю новую версию Hub Hotkeys - Menu Hotkeys. Открывайте различные меню в Хабе, Псайканиуме и соло-игре с помощью горячих клавиш.",
 ["zh-cn"] = "经同志dalokraff许可，我发布了Hub Hotkeys - Menu Hotkeys的新版本。通过快捷键打开哀星号、灵能室和单人游戏中的各种菜单。",
 ["zh-tw"] = "經同志dalokraff許可，我發布了Hub Hotkeys - Menu Hotkeys的新版本。透過快捷鍵打開哀星號、靈能室和單人遊戲中的各種選單。",
		de = "Mit Genehmigung von Genosse dalokraff veröffentliche ich eine neue Version von Hub Hotkeys - Menu Hotkeys. Öffnen Sie verschiedene Menüs im Hub, Psykhanium und Solo-Spiel mit Hotkeys.",
		fr = "Avec la permission du camarade dalokraff, je publie une nouvelle version de Hub Hotkeys - Menu Hotkeys. Ouvrez divers menus depuis le Hub, le Psykhanium et le jeu solo avec des raccourcis.",
		ja = "同志dalokraffの許可を得て、Hub Hotkeys - Menu Hotkeysの新バージョンを公開します。ホットキーでハブ、プシカニウム、ソロプレイの各種メニューを開きます。",
		ko = "동지 dalokraff의 허가를 받아 Hub Hotkeys - Menu Hotkeys의 새 버전을 게시합니다. 단축키로 허브, 프시카니움, 솔로 플레이의 다양한 메뉴를 엽니다.",
		it = "Con il permesso del compagno dalokraff, pubblico una nuova versione di Hub Hotkeys - Menu Hotkeys. Apri vari menu dall'Hub, dal Psykhanium e dal Solo Play con tasti di scelta rapida.",
		pl = "Za zgodą towarzysza dalokraff publikuję nową wersję Hub Hotkeys - Menu Hotkeys. Otwieraj różne menu w Hubie, Psykanium i trybie Solo za pomocą skrótów klawiszowych.",
		es = "Con permiso del camarada dalokraff, publico una nueva versión de Hub Hotkeys - Menu Hotkeys. Abra varios menús desde el Centro, el Psykhanium y el modo Solitario con teclas rápidas.",
 ["pt-br"] = "Com a permissão do camarada dalokraff, estou publicando uma nova versão do Hub Hotkeys - Menu Hotkeys. Abra vários menus do Hub, do Psykhanium e do Solo Play com teclas de atalho.",
	},
	settings_group = {
		en = "Settings",
		ru = "Настройки",
 ["zh-cn"] = "设置",
 ["zh-tw"] = "設定",
		de = "Einstellungen",
		fr = "Paramètres",
		ja = "設定",
		ko = "설정",
		it = "Impostazioni",
		pl = "Ustawienia",
		es = "Ajustes",
 ["pt-br"] = "Configurações",
	},
	enable_in_psykhanium = {
		en = "Enable Hotkeys in the Psykhanium",
		ru = "Включить горячие клавиши в Псайканиуме",
 ["zh-cn"] = "在灵能室启用快捷键",
 ["zh-tw"] = "在靈能室啟用快捷鍵",
		de = "Hotkeys im Psykhanium aktivieren",
		fr = "Activer les raccourcis dans le Psykhanium",
		ja = "プシカニウムでホットキーを有効にする",
		ko = "프시카니움에서 단축키 활성화",
		it = "Abilita hotkey nel Psykhanium",
		pl = "Włącz skróty klawiszowe w Psykanium",
		es = "Habilitar teclas rápidas en el Psykhanium",
 ["pt-br"] = "Ativar teclas de atalho no Psykhanium",
	},
	enable_in_soloplay = {
		en = "Enable Hotkeys in Solo Play",
		ru = "Включить горячие клавиши в соло-игре",
 ["zh-cn"] = "在单人游戏中启用快捷键",
 ["zh-tw"] = "在單人遊戲中啟用快捷鍵",
		de = "Hotkeys im Solo-Spiel aktivieren",
		fr = "Activer les raccourcis en jeu solo",
		ja = "ソロプレイでホットキーを有効にする",
		ko = "솔로 플레이에서 단축키 활성화",
		it = "Abilita hotkey in Solo Play",
		pl = "Włącz skróty klawiszowe w trybie Solo",
		es = "Habilitar teclas rápidas en el modo Solitario",
 ["pt-br"] = "Ativar teclas de atalho no Solo Play",
	},
	enable_in_soloplay_description = {
		en = "Allows hotkeys to open menus while playing a Solo Play mission (offline).",
		ru = "Разрешает открывать меню горячими клавишами во время соло-миссии (офлайн).",
 ["zh-cn"] = "允许在单人游戏（离线）任务中使用快捷键打开菜单。",
 ["zh-tw"] = "允許在單人遊戲（離線）任務中使用快捷鍵打開選單。",
		de = "Ermöglicht das Öffnen von Menüs mit Hotkeys während einer Solo-Mission (offline).",
		fr = "Permet d'ouvrir des menus avec des raccourcis lors d'une mission solo (hors ligne).",
		ja = "ソロプレイミッション（オフライン）中にホットキーでメニューを開くことを許可します。",
		ko = "솔로 플레이 미션(오프라인) 중 단축키로 메뉴를 열 수 있습니다.",
		it = "Permette di aprire menu con hotkey durante una missione in Solo Play (offline).",
		pl = "Pozwala otwierać menu za pomocą skrótów podczas misji Solo (offline).",
		es = "Permite abrir menús con teclas rápidas durante una misión en Solitario (sin conexión).",
 ["pt-br"] = "Permite abrir menus com teclas de atalho durante uma missão Solo Play (offline).",
	},
	close_menu_with_hotkey = {
		en = "Close menus",
		ru = "Закрытие меню клавишами",
 ["zh-cn"] = "关闭菜单",
 ["zh-tw"] = "關閉選單",
		de = "Menüs schließen",
		fr = "Fermer les menus",
		ja = "メニューを閉じる",
		ko = "메뉴 닫기",
		it = "Chiudi menu",
		pl = "Zamknij menu",
		es = "Cerrar menús",
 ["pt-br"] = "Fechar menus",
	},
	close_menu_with_hotkey_description = {
		en = "Enables the closing of menus with their respective hotkeys.",
		ru = "Позволяет закрывать меню с помощью соответствующих горячих клавиш.",
 ["zh-cn"] = "允许用对应的快捷键关闭菜单。",
 ["zh-tw"] = "允許用對應的快捷鍵關閉選單。",
		de = "Ermöglicht das Schließen von Menüs mit den entsprechenden Hotkeys.",
		fr = "Permet de fermer les menus avec leurs raccourcis respectifs.",
		ja = "それぞれのホットキーでメニューを閉じられるようにします。",
		ko = "해당 단축키로 메뉴를 닫을 수 있게 합니다.",
		it = "Consente di chiudere i menu con i rispettivi hotkey.",
		pl = "Umożliwia zamykanie menu za pomocą odpowiednich skrótów klawiszowych.",
		es = "Permite cerrar los menús con sus respectivas teclas rápidas.",
 ["pt-br"] = "Permite fechar os menus com suas respectivas teclas de atalho.",
	},

	hotkeys_group = {
		en = "Hotkeys",
		ru = "Горячие клавиши",
 ["zh-cn"] = "快捷键",
 ["zh-tw"] = "快捷鍵",
		de = "Hotkeys",
		fr = "Raccourcis",
		ja = "ホットキー",
		ko = "단축키",
		it = "Tasti rapidi",
		pl = "Skróty klawiszowe",
		es = "Teclas rápidas",
 ["pt-br"] = "Teclas de atalho",
	},

-- Inventory
	open_inventory_view_key = {
		en = "Inventory",
		ru = "Инвентарь",
 ["zh-cn"] = "库存",
 ["zh-tw"] = "庫存",
		de = "Inventar",
		fr = "Inventaire",
		ja = "インベントリ",
		ko = "인벤토리",
		it = "Inventario",
		pl = "Ekwipunek",
		es = "Inventario",
 ["pt-br"] = "Inventário",
	},
	open_inventory_view_key_description = {
		en = "Opens the Inventory view.",
		ru = "Открывает меню инвентаря.",
 ["zh-cn"] = "打开库存界面。",
 ["zh-tw"] = "打開庫存介面。",
		de = "Öffnet die Inventaransicht.",
		fr = "Ouvre la vue de l'inventaire.",
		ja = "インベントリビューを開きます。",
		ko = "인벤토리 화면을 엽니다.",
		it = "Apre la vista dell'inventario.",
		pl = "Otwiera widok ekwipunku.",
		es = "Abre la vista de inventario.",
 ["pt-br"] = "Abre a visualização do inventário.",
	},

-- Barber
	open_barber_view_key = {
		en = "Barber-chirurgeon",
		ru = "Парикмахер-хирург",
 ["zh-cn"] = "理发师兼外科医生",
 ["zh-tw"] = "理髮師兼外科醫生",
		de = "Barbier-Chirurg",
		fr = "Barbier-chirurgien",
		ja = "理容師兼外科医",
		ko = "이발사 겸 외과의",
		it = "Barbiere-chirurgo",
		pl = "Fryzjer-chirurg",
		es = "Barbero-cirujano",
 ["pt-br"] = "Barbeiro-cirurgião",
	},
	open_barber_view_key_description = {
		en = "Opens the character appearance menu.",
		ru = "Открывает меню изменения внешности персонажа.",
 ["zh-cn"] = "打开理发师兼外科医生界面。",
 ["zh-tw"] = "打開理髮師兼外科醫生介面。",
		de = "Öffnet das Menü zur Änderung des Charakteraussehens.",
		fr = "Ouvre le menu de modification de l'apparence du personnage.",
		ja = "キャラクターの外見変更メニューを開きます。",
		ko = "캐릭터 외형 변경 메뉴를 엽니다.",
		it = "Apre il menu di modifica dell'aspetto del personaggio.",
		pl = "Otwiera menu zmiany wyglądu postaci.",
		es = "Abre el menú de cambio de apariencia del personaje.",
 ["pt-br"] = "Abre o menu de alteração da aparência do personagem.",
	},

-- Sire Melk's Requisitorium
	open_requisitorium_view_key = {
		en = "Sire Melk's Requisitorium",
		ru = "Реквизиторий Сира Мелка",
 ["zh-cn"] = "梅尔克大人的采购店",
 ["zh-tw"] = "梅爾克大人的採購店",
		de = "Requisitorium von Sire Melk",
		fr = "Réquisitoire de Sire Melk",
		ja = "サー・メルクの調達所",
		ko = "사이어 멜크의 조달소",
		it = "Requisitorium di Sire Melk",
		pl = "Rekwizytorium Sir Melka",
		es = "Requisitorio de Sire Melk",
 ["pt-br"] = "Requisitório de Sire Melk",
	},
	open_requisitorium_view_key_description = {
		en = "Opens Sire Melk's Requisitorium root menu.",
		ru = "Открывает корневое меню Реквизитория Сира Мелка.",
 ["zh-cn"] = "打开梅尔克大人的采购店主菜单。",
 ["zh-tw"] = "打開梅爾克大人的採購店主選單。",
		de = "Öffnet das Hauptmenü des Requisitoriums von Sire Melk.",
		fr = "Ouvre le menu principal du Réquisitoire de Sire Melk.",
		ja = "サー・メルクの調達所のルートメニューを開きます。",
		ko = "사이어 멜크의 조달소 루트 메뉴를 엽니다.",
		it = "Apre il menu principale del Requisitorium di Sire Melk.",
		pl = "Otwiera menu główne Rekwizytorium Sir Melka.",
		es = "Abre el menú principal del Requisitorio de Sire Melk.",
 ["pt-br"] = "Abre o menu principal do Requisitório de Sire Melk.",
	},

-- Contracts
	open_contracts_view_key = {
		en = "Contracts",
		ru = "Контракты",
 ["zh-cn"] = "协议",
 ["zh-tw"] = "合約",
		de = "Verträge",
		fr = "Contrats",
		ja = "契約",
		ko = "계약",
		it = "Contratti",
		pl = "Kontrakty",
		es = "Contratos",
 ["pt-br"] = "Contratos",
	},
	open_contracts_view_key_description = {
		en = "Opens the Melk root menu and navigates into Contracts.",
		ru = "Открывает корневое меню Мелка и переходит в Контракты.",
 ["zh-cn"] = "打开梅尔克大人主菜单并进入合同界面。",
 ["zh-tw"] = "打開梅爾克大人主選單並進入合約介面。",
		de = "Öffnet das Melk-Hauptmenü und navigiert zu den Verträgen.",
		fr = "Ouvre le menu principal de Melk et accède aux contrats.",
		ja = "メルクのルートメニューを開き、契約画面に遷移します。",
		ko = "멜크 루트 메뉴를 열고 계약 화면으로 이동합니다.",
		it = "Apre il menu principale di Melk e naviga nei contratti.",
		pl = "Otwiera menu główne Melka i przechodzi do kontraktów.",
		es = "Abre el menú principal de Melk y accede a los contratos.",
 ["pt-br"] = "Abre o menu principal do Melk e navega até os contratos.",
	},
	contracts_open_delay = {
		en = "Contracts Menu Delay",
		ru = "Задержка меню Контрактов",
 ["zh-cn"] = "合同菜单延迟",
 ["zh-tw"] = "合約選單延遲",
		de = "Verzögerung des Vertragsmenüs",
		fr = "Délai du menu des contrats",
		ja = "契約メニューの遅延",
		ko = "계약 메뉴 지연",
		it = "Ritardo del menu contratti",
		pl = "Opóźnienie menu kontraktów",
		es = "Retraso del menú de contratos",
 ["pt-br"] = "Atraso do menu de contratos",
	},
	contracts_open_delay_description = {
		en = "Delay before pressing the first option inside Melk's root menu to enter Contracts. Increase if the navigation does not fire.",
		ru = "Задержка перед нажатием первой опции в корневом меню Мелка для входа в Контракты. Увеличьте, если переход не срабатывает.",
 ["zh-cn"] = "按下梅尔克大人主菜单中第一个选项进入合同前的延迟。如果导航未触发，请增加此值。",
 ["zh-tw"] = "按下梅爾克大人主選單中第一個選項進入合約前的延遲。如果導覽未觸發，請增加此值。",
		de = "Verzögerung, bevor die erste Option im Melk-Hauptmenü gedrückt wird. Erhöhen Sie den Wert, wenn die Navigation nicht ausgelöst wird.",
		fr = "Délai avant d'appuyer sur la première option du menu principal de Melk pour entrer dans les contrats.",
		ja = "メルクのルートメニューで最初のオプションを押すまでの遅延。遷移しない場合はこの値を増やしてください。",
		ko = "멜크 루트 메뉴에서 첫 번째 옵션을 누르기 전 지연입니다. 이동이 안 되면 이 값을 늘리세요.",
		it = "Ritardo prima di premere la prima opzione nel menu principale di Melk per entrare nei contratti.",
		pl = "Opóźnienie przed naciśnięciem pierwszej opcji w menu głównym Melka, aby wejść do kontraktów.",
		es = "Retraso antes de pulsar la primera opción en el menú principal de Melk para entrar en los contratos.",
 ["pt-br"] = "Atraso antes de pressionar a primeira opção no menu principal do Melk para entrar nos contratos.",
	},

-- Crafting
	open_crafting_view_key = {
		en = "Crafting",
		ru = "Кузница",
 ["zh-cn"] = "锻造",
 ["zh-tw"] = "鍛造",
		de = "Handwerk",
		fr = "Artisanat",
		ja = "クラフト",
		ko = "제작",
		it = "Creazione",
		pl = "Wytwarzanie",
		es = "Fabricación",
 ["pt-br"] = "Fabricação",
	},
	open_crafting_view_key_description = {
		en = "Opens the Crafting view.",
		ru = "Открывает меню создания и улучшения предметов.",
 ["zh-cn"] = "打开锻造界面。",
 ["zh-tw"] = "打開鍛造介面。",
		de = "Öffnet die Handwerksansicht.",
		fr = "Ouvre la vue de l'artisanat.",
		ja = "クラフトビューを開きます。",
		ko = "제작 화면을 엽니다.",
		it = "Apre la vista di creazione.",
		pl = "Otwiera widok wytwarzania.",
		es = "Abre la vista de fabricación.",
 ["pt-br"] = "Abre a visualização de fabricação.",
	},

-- Armoury Exchange
	open_credits_vendor_view_key = {
		en = "Armoury Exchange",
		ru = "Оружейная",
 ["zh-cn"] = "军械交易所",
 ["zh-tw"] = "軍械交易所",
		de = "Waffenkammer",
		fr = "Armurerie",
		ja = "武器取引所",
		ko = "무기 거래소",
		it = "Armeria",
		pl = "Zbrojownia",
		es = "Armería",
 ["pt-br"] = "Arsenal",
	},
	open_credits_vendor_view_key_description = {
		en = "Opens the menu for purchasing Weapons and Curios.",
		ru = "Открывает меню покупки оружия и реликвий.",
 ["zh-cn"] = "打开军械兑换处，使用金币购买武器与饰品。",
 ["zh-tw"] = "打開軍械交易所介面。",
		de = "Öffnet das Menü zum Kauf von Waffen und Kuriositäten.",
		fr = "Ouvre le menu d'achat d'armes et de curiosités.",
		ja = "武器と珍品の購入メニューを開きます。",
		ko = "무기와 희귀품 구매 메뉴를 엽니다.",
		it = "Apre il menu per l'acquisto di armi e curiosità.",
		pl = "Otwiera menu zakupu broni i osobliwości.",
		es = "Abre el menú para comprar armas y curiosidades.",
 ["pt-br"] = "Abre o menu para comprar armas e curiosidades.",
	},

-- Mission Board
	open_mission_board_view_key = {
		en = "Mission Board",
		ru = "Доска миссий",
 ["zh-cn"] = "任务面板",
 ["zh-tw"] = "任務面板",
		de = "Missionstafel",
		fr = "Tableau des missions",
		ja = "ミッションボード",
		ko = "미션 보드",
		it = "Tabellone missioni",
		pl = "Tablica misji",
		es = "Tablero de misiones",
 ["pt-br"] = "Painel de missões",
	},
	open_mission_board_view_key_description = {
		en = "Opens the Mission Board view.",
		ru = "Открывает меню выбора миссий.",
 ["zh-cn"] = "打开任务面板。",
 ["zh-tw"] = "打開任務面板。",
		de = "Öffnet die Missionsansicht.",
		fr = "Ouvre la vue du tableau des missions.",
		ja = "ミッションボードのビューを開きます。",
		ko = "미션 보드 화면을 엽니다.",
		it = "Apre la vista del tabellone missioni.",
		pl = "Otwiera widok tablicy misji.",
		es = "Abre la vista del tablero de misiones.",
 ["pt-br"] = "Abre a visualização do painel de missões.",
	},

-- Premium Store
	open_premium_store_view_key = {
		en = "Premium Store",
		ru = "Премиум-магазин",
 ["zh-cn"] = "高级商店",
 ["zh-tw"] = "高級商店",
		de = "Premium-Shop",
		fr = "Boutique premium",
		ja = "プレミアムストア",
		ko = "프리미엄 상점",
		it = "Negozio premium",
		pl = "Sklep premium",
		es = "Tienda premium",
 ["pt-br"] = "Loja premium",
	},
	open_premium_store_view_key_description = {
		en = "Opens the Premium Store view.",
		ru = "Открывает магазин с премиумным снаряжением.",
 ["zh-cn"] = "打开付费外观商店界面。",
 ["zh-tw"] = "打開高級商店介面。",
		de = "Öffnet die Premium-Shop-Ansicht.",
		fr = "Ouvre la vue de la boutique premium.",
		ja = "プレミアムストアのビューを開きます。",
		ko = "프리미엄 상점 화면을 엽니다.",
		it = "Apre la vista del negozio premium.",
		pl = "Otwiera widok sklepu premium.",
		es = "Abre la vista de la tienda premium.",
 ["pt-br"] = "Abre a visualização da loja premium.",
	},

-- Mortis Trials
	open_training_grounds_view_key = {
		en = "Mortis Trials",
		ru = "Испытания Мортис",
 ["zh-cn"] = "莫蒂斯试炼",
 ["zh-tw"] = "莫蒂斯試煉",
		de = "Mortis-Prüfungen",
		fr = "Épreuves de Mortis",
		ja = "モーティスの試練",
		ko = "모르티스 시험",
		it = "Prove di Mortis",
		pl = "Próby Mortis",
		es = "Pruebas de Mortis",
 ["pt-br"] = "Julgamentos de Mortis",
	},
	open_training_grounds_view_key_description = {
		en = "Opens the Mortis Trials selection menu.",
		ru = "Открывает меню выбора Испытаний Мортис.",
 ["zh-cn"] = "打开莫蒂斯试炼选择菜单。",
 ["zh-tw"] = "打開莫蒂斯試煉選擇選單。",
		de = "Öffnet das Menü zur Auswahl der Mortis-Prüfungen.",
		fr = "Ouvre le menu de sélection des Épreuves de Mortis.",
		ja = "モーティスの試練選択メニューを開きます。",
		ko = "모르티스 시험 선택 메뉴를 엽니다.",
		it = "Apre il menu di selezione delle Prove di Mortis.",
		pl = "Otwiera menu wyboru Prób Mortis.",
		es = "Abre el menú de selección de Pruebas de Mortis.",
 ["pt-br"] = "Abre o menu de seleção dos Julgamentos de Mortis.",
	},

-- Meat Grinder
	open_meatgrinder_view_key = {
		en = "Meat Grinder",
		ru = "Мясорубка",
 ["zh-cn"] = "绞肉机",
 ["zh-tw"] = "絞肉機",
		de = "Fleischwolf",
		fr = "Hachoir",
		ja = "ミートグラインダー",
		ko = "고기 분쇄기",
		it = "Tritacarne",
		pl = "Młynek do mięsa",
		es = "Picadora de carne",
 ["pt-br"] = "Moinho de Carne",
	},
	open_meatgrinder_view_key_description = {
		en = "Starts the Meat Grinder training mission directly.",
		ru = "Запускает тренировочную арену - Мясорубку.",
 ["zh-cn"] = "直接开始绞肉机训练任务。",
 ["zh-tw"] = "直接開始絞肉機訓練任務。",
		de = "Startet direkt die Trainingsmission Fleischwolf.",
		fr = "Lance directement la mission d'entraînement « Hachoir ».",
		ja = "ミートグラインダーのトレーニングミッションを直接開始します。",
		ko = "고기 분쇄기 훈련 미션을 직접 시작합니다.",
		it = "Avvia direttamente la missione di addestramento «Tritacarne».",
		pl = "Uruchamia bezpośrednio misję treningową Młynek do mięsa.",
		es = "Inicia directamente la misión de entrenamiento «Picadora de carne».",
 ["pt-br"] = "Inicia diretamente a missão de treinamento «Moinho de Carne».",
	},

-- Social menu
	open_social_view_key = {
		en = "Social menu",
		ru = "Социальное меню",
 ["zh-cn"] = "社交菜单",
 ["zh-tw"] = "社群選單",
		de = "Soziales Menü",
		fr = "Menu social",
		ja = "ソーシャルメニュー",
		ko = "소셜 메뉴",
		it = "Menu sociale",
		pl = "Menu społecznościowe",
		es = "Menú social",
 ["pt-br"] = "Menu social",
	},
	open_social_view_key_description = {
		en = "Opens the menu for managing strike team, friends, and invitations.",
		ru = "Открывает меню управления ударной группой, друзьями, приглашениями.",
 ["zh-cn"] = "打开管理打击小队、好友和邀请的菜单。",
 ["zh-tw"] = "開啟管理打擊小隊、好友和邀請的選單。",
		de = "Öffnet das Menü zur Verwaltung des Einsatzteams, von Freunden und Einladungen.",
		fr = "Ouvre le menu de gestion de l'équipe d'assaut, des amis et des invitations.",
		ja = "ストライクチーム、フレンド、招待を管理するメニューを開きます。",
		ko = "스트라이크 팀, 친구, 초대를 관리하는 메뉴를 엽니다.",
		it = "Apre il menu per la gestione della squadra d'assalto, degli amici e degli inviti.",
		pl = "Otwiera menu zarządzania drużyną uderzeniową, znajomymi i zaproszeniami.",
		es = "Abre el menú para gestionar el equipo de ataque, amigos e invitaciones.",
 ["pt-br"] = "Abre o menu para gerenciar a equipe de ataque, amigos e convites.",
	},

-- Commissary (Cosmetics)
	open_commissary_view_key = {
		en = "Commissary (Cosmetics)",
		ru = "Комиссариат (косметика)",
 ["zh-cn"] = "杂货店（外观）",
 ["zh-tw"] = "雜貨店（外觀）",
		de = "Kommissariat (Kosmetik)",
		fr = "Commissariat (cosmétiques)",
		ja = "コミサリー（コスメ）",
		ko = "위관 상점 (외형)",
		it = "Commissariato (cosmetici)",
		pl = "Komisariat (kosmetyki)",
		es = "Comisaría (cosméticos)",
 ["pt-br"] = "Comissariado (cosméticos)",
	},
	open_commissary_view_key_description = {
		en = "Opens the menu for purchasing cosmetic items for weapons and operatives.",
		ru = "Открывает меню покупки косметических предметов для оружия и оперативников.",
 ["zh-cn"] = "打开购买武器和特工外观物品的菜单。",
 ["zh-tw"] = "打開購買武器和特工外觀物品的選單。",
		de = "Öffnet das Menü zum Kauf von kosmetischen Gegenständen für Waffen und Agenten.",
		fr = "Ouvre le menu d'achat d'objets cosmétiques pour les armes et les opératifs.",
		ja = "武器とオペレーター用のコスメティックアイテムを購入するメニューを開きます。",
		ko = "무기와 요원용 외형 아이템을 구매하는 메뉴를 엽니다.",
		it = "Apre il menu per l'acquisto di oggetti cosmetici per armi e operatori.",
		pl = "Otwiera menu zakupu przedmiotów kosmetycznych dla broni i agentów.",
		es = "Abre el menú para comprar artículos cosméticos para armas y operativos.",
 ["pt-br"] = "Abre o menu para comprar itens cosméticos para armas e operativos.",
	},

-- Penance
	open_penance_view_key = {
		en = "Shrine Penitentax",
		ru = "Святилище Искуплений",
 ["zh-cn"] = "神龛忏悔者",
 ["zh-tw"] = "神龕懺悔者",
		de = "Schrein der Buße",
		fr = "Autel pénitentiel",
		ja = "苦行の神殿",
		ko = "참회 신전",
		it = "Santuario penitenziale",
		pl = "Sanktuarium pokuty",
		es = "Santuario penitencial",
 ["pt-br"] = "Santuário penitencial",
	},
	open_penance_view_key_description = {
		en = "Opens the Penance view.",
		ru = "Открывает меню искуплений.",
 ["zh-cn"] = "打开苦修界面。",
 ["zh-tw"] = "打開苦修介面。",
		de = "Öffnet die Bußansicht.",
		fr = "Ouvre la vue des pénitences.",
		ja = "ペナンスビューを開きます。",
		ko = "참회 화면을 엽니다.",
		it = "Apre la vista delle penitenze.",
		pl = "Otwiera widok pokut.",
		es = "Abre la vista de penitencias.",
 ["pt-br"] = "Abre a visualização de penitências.",
	},

-- Havoc Mode
	open_havoc_view_key = {
		en = "Havoc Mode",
		ru = "Режим Хавок",
 ["zh-cn"] = "浩劫模式",
 ["zh-tw"] = "浩劫模式",
		de = "Havoc-Modus",
		fr = "Mode Havoc",
		ja = "ハボックモード",
		ko = "하복 모드",
		it = "Modalità Flagello",
		pl = "Tryb Havoc",
		es = "Modo Havoc",
 ["pt-br"] = "Modo Havoc",
	},
	open_havoc_view_key_description = {
		en = "Opens the Havoc menu.",
		ru = "Открывает меню Хавока.",
 ["zh-cn"] = "打开浩劫模式选择界面。",
 ["zh-tw"] = "開啟浩劫模式選擇介面。",
		de = "Öffnet das Havoc-Menü.",
		fr = "Ouvre le menu Havoc.",
		ja = "ハボックメニューを開きます。",
		ko = "하복 메뉴를 엽니다.",
		it = "Apre il menu Flagello.",
		pl = "Otwiera menu Havoc.",
		es = "Abre el menú Havoc.",
 ["pt-br"] = "Abre o menu Havoc.",
	},

-- Expedition Mode
	open_expedition_view_key = {
		en = "Expedition Mode",
		ru = "Режим Экспедиции",
 ["zh-cn"] = "远征模式",
 ["zh-tw"] = "遠徵模式",
		de = "Expeditions-Modus",
		fr = "Mode Expédition",
		ja = "遠征モード",
		ko = "원정 모드",
		it = "Modalità Spedizione",
		pl = "Tryb Ekspedycji",
		es = "Modo Expedición",
 ["pt-br"] = "Modo Expedição",
	},
	open_expedition_view_key_description = {
		en = "Opens the Expedition Menu.",
		ru = "Открывает меню Экспедиций.",
 ["zh-cn"] = "打开远征模式选择界面。",
 ["zh-tw"] = "開啟遠徵模式選擇介面。",
		de = "Öffnet das Expeditions-Menü.",
		fr = "Ouvre le menu Expédition.",
		ja = "遠征メニューを開きます。",
		ko = "원정 메뉴를 엽니다.",
		it = "Apre il menu Spedizione.",
		pl = "Otwiera menu Ekspedycji.",
		es = "Abre el menú Expedición.",
 ["pt-br"] = "Abre o menu Expedição.",
	},

-- Quit Game
	quit_game_key = {
		en = "Quit Game",
		ru = "Выйти из игры",
 ["zh-cn"] = "退出游戏",
 ["zh-tw"] = "退出遊戲",
		de = "Spiel beenden",
		fr = "Quitter le jeu",
		ja = "ゲームを終了",
		ko = "게임 종료",
		it = "Esci dal gioco",
		pl = "Zakończ grę",
		es = "Salir del juego",
 ["pt-br"] = "Sair do jogo",
	},
	quit_game_key_description = {
		en = "Instantly quits the game.",
		ru = "Немедленно закрывает игру.",
 ["zh-cn"] = "立即退出游戏。",
 ["zh-tw"] = "立即退出遊戲。",
		de = "Beendet das Spiel sofort.",
		fr = "Quitte immédiatement le jeu.",
		ja = "ゲームを即座に終了します。",
		ko = "게임을 즉시 종료합니다.",
		it = "Esce immediatamente dal gioco.",
		pl = "Natychmiast zamyka grę.",
		es = "Sale inmediatamente del juego.",
 ["pt-br"] = "Sai imediatamente do jogo.",
	},

	debug_group = {
		en = "Debug",
		ru = "Отладка",
 ["zh-cn"] = "调试",
 ["zh-tw"] = "除錯",
		de = "Debug",
		fr = "Débogage",
		ja = "デバッグ",
		ko = "디버그",
		it = "Debug",
		pl = "Debugowanie",
		es = "Depuración",
 ["pt-br"] = "Depuração",
	},

	unit_ms = {
		en = "ms",
		ru = "мс",
 ["zh-cn"] = "毫秒",
 ["zh-tw"] = "毫秒",
		de = "ms",
		fr = "ms",
		ja = "ミリ秒",
		ko = "밀리초",
		it = "ms",
		pl = "ms",
		es = "ms",
 ["pt-br"] = "ms",
	},

	group_finder_open_delay = {
		en = "Havoc Group Finder Delay",
		ru = "Задержка поиска группы Хавок",
 ["zh-cn"] = "浩劫组队寻找器延迟",
 ["zh-tw"] = "浩劫組隊尋找器延遲",
		de = "Havoc-Gruppensuche Verzögerung",
		fr = "Délai de recherche de groupe Havoc",
		ja = "ハボックグループ検索遅延",
		ko = "하복 그룹 찾기 지연",
		it = "Ritardo ricerca gruppo Flagello",
		pl = "Opóźnienie wyszukiwania grupy Havoc",
		es = "Retraso del buscador de grupo Havoc",
 ["pt-br"] = "Atraso do buscador de grupo Havoc",
	},
	group_finder_open_delay_description = {
		en = "Delay before the Group Finder opens from the Havoc view. Increase if the Havoc view closes on its own.",
		ru = "Задержка перед открытием поиска группы из меню Хавока. Увеличьте, если меню Хавока закрывается само.",
 ["zh-cn"] = "从浩劫界面打开组队寻找器前的延迟。如果浩劫界面自动关闭，请增加此值。",
 ["zh-tw"] = "從浩劫介面打開組隊尋找器前的延遲。如果浩劫介面自動關閉，請增加此值。",
		de = "Verzögerung, bevor die Gruppensuche aus der Havoc-Ansicht geöffnet wird.",
		fr = "Délai avant l'ouverture du recherche de groupe depuis la vue Havoc.",
		ja = "ハボックビューからグループ検索を開くまでの遅延。",
		ko = "하복 화면에서 그룹 찾기를 열기 전 지연입니다.",
		it = "Ritardo prima dell'apertura della ricerca gruppo dalla vista Flagello.",
		pl = "Opóźnienie przed otwarciem wyszukiwania grupy z widoku Havoc.",
		es = "Retraso antes de abrir el buscador de grupo desde la vista Havoc.",
 ["pt-br"] = "Atraso antes de abrir o buscador de grupo da visualização Havoc.",
	},
}

return localizations
