-- menu_hotkeys_localization.lua
local mod = get_mod("menu_hotkeys")

return {
	mod_name = {
		en = "Menu Hotkeys",
		ru = "Горячие клавиши меню",
 ["zh-cn"] = "菜单快捷键",
 ["zh-tw"] = "選單快捷鍵",
		de = "Menü-Hotkeys",
		fr = "Raccourcis des menus",
		ja = "メニューホットキー",
		ko = "메뉴 단축키",
		it = "Tasti rapidi dei menu",
		pl = "Skróty klawiszowe menu",
		es = "Teclas rápidas de menú",
 ["pt-br"] = "Atalhos do menu",
	},
	mod_description = {
		en = "Open various menus from the Hub, Psykhanium and Solo Play with hotkeys.",
		ru = "Menu Hotkeys - Открывайте различные меню в Хабе, Псайканиуме и соло-игре с помощью горячих клавиш.",
 ["zh-cn"] = "通过快捷键打开哀星号、灵能室和单人游戏中的各种菜单。",
 ["zh-tw"] = "透過快捷鍵打開哀星號、靈能室和單人遊戲中的各種選單。",
		de = "Öffnen Sie verschiedene Menüs im Hub, im Psykhanium und im Solo-Spiel mit Hotkeys.",
		fr = "Ouvrez divers menus depuis le Hub, le Psykhanium et le jeu solo avec des raccourcis.",
		ja = "ホットキーでハブ、プシカニウム、ソロプレイの各種メニューを開きます。",
		ko = "단축키로 허브, 프시카니움, 솔로 플레이의 다양한 메뉴를 엽니다.",
		it = "Apri vari menu dall'Hub, dal Psykhanium e dal Solo Play con tasti di scelta rapida.",
		pl = "Otwieraj różne menu w Hubie, Psykanium i trybie Solo za pomocą skrótów klawiszowych.",
		es = "Abra varios menús desde el Centro, el Psykhanium y el modo Solitario con teclas rápidas.",
 ["pt-br"] = "Abra vários menus do Hub, do Psykhanium e do Solo Play com teclas de atalho.",
	},
	enable_in_psykhanium = {
		en = "Enable Hotkeys in the Psykhanium",
		ru = "Включить горячие клавиши в Псайканиуме",
 ["zh-cn"] = "在灵能室启用快捷键",
 ["zh-tw"] = "在靈能室啟用快捷鍵",
		de = "Hotkeys im Psykhanium aktivieren",
		fr = "Activer les raccourcis dans le Psykhanium",
		ja = "プシカニウムでホットキーを有効にする",
		ko = "프시카니움에서 단축키 활성화",
		it = "Abilita hotkey nel Psykhanium",
		pl = "Włącz skróty klawiszowe w Psykanium",
		es = "Habilitar teclas rápidas en el Psykhanium",
 ["pt-br"] = "Ativar teclas de atalho no Psykhanium",
	},
	enable_in_soloplay = {
		en = "Enable Hotkeys in Solo Play",
		ru = "Включить горячие клавиши в соло-игре",
 ["zh-cn"] = "在单人游戏中启用快捷键",
 ["zh-tw"] = "在單人遊戲中啟用快捷鍵",
		de = "Hotkeys im Solo-Spiel aktivieren",
		fr = "Activer les raccourcis en jeu solo",
		ja = "ソロプレイでホットキーを有効にする",
		ko = "솔로 플레이에서 단축키 활성화",
		it = "Abilita hotkey in Solo Play",
		pl = "Włącz skróty klawiszowe w trybie Solo",
		es = "Habilitar teclas rápidas en el modo Solitario",
 ["pt-br"] = "Ativar teclas de atalho no Solo Play",
	},
	enable_in_soloplay_description = {
		en = "Allows hotkeys to open menus while playing a Solo Play mission (offline).",
		ru = "Разрешает открывать меню горячими клавишами во время соло-миссии (офлайн).",
 ["zh-cn"] = "允许在单人游戏（离线）任务中使用快捷键打开菜单。",
 ["zh-tw"] = "允許在單人遊戲（離線）任務中使用快捷鍵打開選單。",
		de = "Ermöglicht das Öffnen von Menüs mit Hotkeys während einer Solo-Mission (offline).",
		fr = "Permet d'ouvrir des menus avec des raccourcis lors d'une mission solo (hors ligne).",
		ja = "ソロプレイミッション（オフライン）中にホットキーでメニューを開くことを許可します。",
		ko = "솔로 플레이 미션(오프라인) 중 단축키로 메뉴를 열 수 있습니다.",
		it = "Permette di aprire menu con hotkey durante una missione in Solo Play (offline).",
		pl = "Pozwala otwierać menu za pomocą skrótów podczas misji Solo (offline).",
		es = "Permite abrir menús con teclas rápidas durante una misión en Solitario (sin conexión).",
 ["pt-br"] = "Permite abrir menus com teclas de atalho durante uma missão Solo Play (offline).",
	},
	close_menu_with_hotkey = {
		en = "Close menus",
		ru = "Закрытие меню клавишами",
 ["zh-cn"] = "关闭菜单",
 ["zh-tw"] = "關閉選單",
		de = "Menüs schließen",
		fr = "Fermer les menus",
		ja = "メニューを閉じる",
		ko = "메뉴 닫기",
		it = "Chiudi menu",
		pl = "Zamknij menu",
		es = "Cerrar menús",
 ["pt-br"] = "Fechar menus",
	},
	close_menu_with_hotkey_description = {
		en = "Enables the closing of menus with their respective hotkeys.",
		ru = "Позволяет закрывать меню с помощью соответствующих горячих клавиш.",
 ["zh-cn"] = "允许用对应的快捷键关闭菜单。",
 ["zh-tw"] = "允許用對應的快捷鍵關閉選單。",
		de = "Ermöglicht das Schließen von Menüs mit den entsprechenden Hotkeys.",
		fr = "Permet de fermer les menus avec leurs raccourcis respectifs.",
		ja = "それぞれのホットキーでメニューを閉じられるようにします。",
		ko = "해당 단축키로 메뉴를 닫을 수 있게 합니다.",
		it = "Consente di chiudere i menu con i rispettivi hotkey.",
		pl = "Umożliwia zamykanie menu za pomocą odpowiednich skrótów klawiszowych.",
		es = "Permite cerrar los menús con sus respectivas teclas rápidas.",
 ["pt-br"] = "Permite fechar os menus com suas respectivas teclas de atalho.",
	},

	-- Barber
	open_barber_view_key = {
		en = "Barber-chirurgeon",
		ru = "Парикмахер-хирург",
 ["zh-cn"] = "理发师兼外科医生",
 ["zh-tw"] = "理髮師兼外科醫生",
		de = "Barbier-Chirurg",
		fr = "Barbier-chirurgien",
		ja = "理容師兼外科医",
		ko = "이발사 겸 외과의",
		it = "Barbiere-chirurgo",
		pl = "Fryzjer-chirurg",
		es = "Barbero-cirujano",
 ["pt-br"] = "Barbeiro-cirurgião",
	},
	open_barber_view_key_description = {
		en = "Opens the character appearance menu.",
		ru = "Открывает меню изменения внешности персонажа.",
 ["zh-cn"] = "打开理发师兼外科医生界面。",
 ["zh-tw"] = "打開理髮師兼外科醫生介面。",
		de = "Öffnet das Menü zur Änderung des Charakteraussehens.",
		fr = "Ouvre le menu de modification de l'apparence du personnage.",
		ja = "キャラクターの外見変更メニューを開きます。",
		ko = "캐릭터 외형 변경 메뉴를 엽니다.",
		it = "Apre il menu di modifica dell'aspetto del personaggio.",
		pl = "Otwiera menu zmiany wyglądu postaci.",
		es = "Abre el menú de cambio de apariencia del personaje.",
 ["pt-br"] = "Abre o menu de alteração da aparência do personagem.",
	},

	-- Contracts
	open_contracts_view_key = {
		en = "Contracts",
		ru = "Контракты",
 ["zh-cn"] = "协议",
 ["zh-tw"] = "合約",
		de = "Verträge",
		fr = "Contrats",
		ja = "契約",
		ko = "계약",
		it = "Contratti",
		pl = "Kontrakty",
		es = "Contratos",
 ["pt-br"] = "Contratos",
	},
	open_contracts_view_key_description = {
		en = "Opens the Contracts view.",
		ru = "Открывает меню управления контрактами.",
 ["zh-cn"] = "打开梅尔克大人的采购店界面。",
 ["zh-tw"] = "打開梅爾克大人的採購店介面。",
		de = "Öffnet die Vertragsansicht.",
		fr = "Ouvre la vue des contrats.",
		ja = "契約ビューを開きます。",
		ko = "계약 화면을 엽니다.",
		it = "Apre la vista dei contratti.",
		pl = "Otwiera widok kontraktów.",
		es = "Abre la vista de contratos.",
 ["pt-br"] = "Abre a visualização de contratos.",
	},

	-- Crafting
	open_crafting_view_key = {
		en = "Crafting",
		ru = "Ковка",
 ["zh-cn"] = "锻造",
 ["zh-tw"] = "鍛造",
		de = "Handwerk",
		fr = "Artisanat",
		ja = "クラフト",
		ko = "제작",
		it = "Creazione",
		pl = "Wytwarzanie",
		es = "Fabricación",
 ["pt-br"] = "Fabricação",
	},
	open_crafting_view_key_description = {
		en = "Opens the Crafting view.",
		ru = "Открывает меню создания и улучшения предметов.",
 ["zh-cn"] = "打开 O-7-7 海德昂界面。",
 ["zh-tw"] = "打開 O-7-7 海德昂介面。",
		de = "Öffnet die Handwerksansicht.",
		fr = "Ouvre la vue de l'artisanat.",
		ja = "クラフトビューを開きます。",
		ko = "제작 화면을 엽니다.",
		it = "Apre la vista di creazione.",
		pl = "Otwiera widok wytwarzania.",
		es = "Abre la vista de fabricación.",
 ["pt-br"] = "Abre a visualização de fabricação.",
	},

	-- Armoury Exchange
	open_credits_vendor_view_key = {
		en = "Armoury Exchange",
		ru = "Оружейный обмен",
 ["zh-cn"] = "军械交易所",
 ["zh-tw"] = "軍械交易所",
		de = "Waffenkammer",
		fr = "Armurerie",
		ja = "武器取引所",
		ko = "무기 거래소",
		it = "Armeria",
		pl = "Zbrojownia",
		es = "Armería",
 ["pt-br"] = "Arsenal",
	},
	open_credits_vendor_view_key_description = {
		en = "Opens the menu for purchasing Weapons and Curios.",
		ru = "Открывает меню покупки оружия и реликвий.",
 ["zh-cn"] = "打开军械交易所界面。",
 ["zh-tw"] = "打開軍械交易所介面。",
		de = "Öffnet das Menü zum Kauf von Waffen und Kuriositäten.",
		fr = "Ouvre le menu d'achat d'armes et de curiosités.",
		ja = "武器と珍品の購入メニューを開きます。",
		ko = "무기와 희귀품 구매 메뉴를 엽니다.",
		it = "Apre il menu per l'acquisto di armi e curiosità.",
		pl = "Otwiera menu zakupu broni i osobliwości.",
		es = "Abre el menú para comprar armas y curiosidades.",
 ["pt-br"] = "Abre o menu para comprar armas e curiosidades.",
	},

	-- Mission Board
	open_mission_board_view_key = {
		en = "Mission Board",
		ru = "Доска миссий",
 ["zh-cn"] = "任务面板",
 ["zh-tw"] = "任務面板",
		de = "Missionstafel",
		fr = "Tableau des missions",
		ja = "ミッションボード",
		ko = "미션 보드",
		it = "Tabellone missioni",
		pl = "Tablica misji",
		es = "Tablero de misiones",
 ["pt-br"] = "Painel de missões",
	},
	open_mission_board_view_key_description = {
		en = "Opens the Mission Board view.",
		ru = "Открывает меню выбора миссий.",
 ["zh-cn"] = "打开任务面板。",
 ["zh-tw"] = "打開任務面板。",
		de = "Öffnet die Missionsansicht.",
		fr = "Ouvre la vue du tableau des missions.",
		ja = "ミッションボードのビューを開きます。",
		ko = "미션 보드 화면을 엽니다.",
		it = "Apre la vista del tabellone missioni.",
		pl = "Otwiera widok tablicy misji.",
		es = "Abre la vista del tablero de misiones.",
 ["pt-br"] = "Abre a visualização do painel de missões.",
	},

	-- Premium Store
	open_premium_store_view_key = {
		en = "Premium Store",
		ru = "Премиум-магазин",
 ["zh-cn"] = "高级商店",
 ["zh-tw"] = "高級商店",
		de = "Premium-Shop",
		fr = "Boutique premium",
		ja = "プレミアムストア",
		ko = "프리미엄 상점",
		it = "Negozio premium",
		pl = "Sklep premium",
		es = "Tienda premium",
 ["pt-br"] = "Loja premium",
	},
	open_premium_store_view_key_description = {
		en = "Opens the Premium Store view.",
		ru = "Открывает магазин с премиумным снаряжением.",
 ["zh-cn"] = "打开准将的服装界面。",
 ["zh-tw"] = "打開准將的服裝介面。",
		de = "Öffnet die Premium-Shop-Ansicht.",
		fr = "Ouvre la vue de la boutique premium.",
		ja = "プレミアムストアのビューを開きます。",
		ko = "프리미엄 상점 화면을 엽니다.",
		it = "Apre la vista del negozio premium.",
		pl = "Otwiera widok sklepu premium.",
		es = "Abre la vista de la tienda premium.",
 ["pt-br"] = "Abre a visualização da loja premium.",
	},

	-- Training Grounds
	open_training_grounds_view_key = {
		en = "Training Grounds",
		ru = "Стрельбище",
 ["zh-cn"] = "训练场",
 ["zh-tw"] = "訓練場",
		de = "Trainingsgelände",
		fr = "Terrain d'entraînement",
		ja = "訓練場",
		ko = "훈련장",
		it = "Poligono di addestramento",
		pl = "Plac treningowy",
		es = "Campo de entrenamiento",
 ["pt-br"] = "Campo de treinamento",
	},
	open_training_grounds_view_key_description = {
		en = "Opens the Training Grounds view.",
		ru = "Открывает меню входа на стрельбище.",
 ["zh-cn"] = "打开灵能室界面。",
 ["zh-tw"] = "打開靈能室介面。",
		de = "Öffnet die Trainingsgelände-Ansicht.",
		fr = "Ouvre la vue du terrain d'entraînement.",
		ja = "訓練場のビューを開きます。",
		ko = "훈련장 화면을 엽니다.",
		it = "Apre la vista del poligono di addestramento.",
		pl = "Otwiera widok placu treningowego.",
		es = "Abre la vista del campo de entrenamiento.",
 ["pt-br"] = "Abre a visualização do campo de treinamento.",
	},

	-- Social menu
	open_social_view_key = {
		en = "Social menu",
		ru = "Социальное меню",
 ["zh-cn"] = "社交菜单",
 ["zh-tw"] = "社群選單",
		de = "Soziales Menü",
		fr = "Menu social",
		ja = "ソーシャルメニュー",
		ko = "소셜 메뉴",
		it = "Menu sociale",
		pl = "Menu społecznościowe",
		es = "Menú social",
 ["pt-br"] = "Menu social",
	},
	open_social_view_key_description = {
		en = "Opens the menu for managing strike team, friends, and invitations.",
		ru = "Открывает меню управления ударной группой, друзьями, приглашениями.",
 ["zh-cn"] = "打开管理打击小队、好友和邀请的菜单。",
 ["zh-tw"] = "開啟管理打擊小隊、好友和邀請的選單。",
		de = "Öffnet das Menü zur Verwaltung des Einsatzteams, von Freunden und Einladungen.",
		fr = "Ouvre le menu de gestion de l'équipe d'assaut, des amis et des invitations.",
		ja = "ストライクチーム、フレンド、招待を管理するメニューを開きます。",
		ko = "스트라이크 팀, 친구, 초대를 관리하는 메뉴를 엽니다.",
		it = "Apre il menu per la gestione della squadra d'assalto, degli amici e degli inviti.",
		pl = "Otwiera menu zarządzania drużyną uderzeniową, znajomymi i zaproszeniami.",
		es = "Abre el menú para gestionar el equipo de ataque, amigos e invitaciones.",
 ["pt-br"] = "Abre o menu para gerenciar a equipe de ataque, amigos e convites.",
	},

	-- Commissary (Cosmetics)
	open_commissary_view_key = {
		en = "Commissary (Cosmetics)",
		ru = "Комиссариат (косметика)",
 ["zh-cn"] = "杂货店（外观）",
 ["zh-tw"] = "雜貨店（外觀）",
		de = "Kommissariat (Kosmetik)",
		fr = "Commissariat (cosmétiques)",
		ja = "コミサリー（コスメ）",
		ko = "위관 상점 (외형)",
		it = "Commissariato (cosmetici)",
		pl = "Komisariat (kosmetyki)",
		es = "Comisaría (cosméticos)",
 ["pt-br"] = "Comissariado (cosméticos)",
	},
	open_commissary_view_key_description = {
		en = "Opens the menu for purchasing cosmetic items for weapons and operatives.",
		ru = "Открывает меню покупки косметических предметов для оружия и оперативников.",
 ["zh-cn"] = "打开购买武器和特工外观物品的菜单。",
 ["zh-tw"] = "打開購買武器和特工外觀物品的選單。",
		de = "Öffnet das Menü zum Kauf von kosmetischen Gegenständen für Waffen und Agenten.",
		fr = "Ouvre le menu d'achat d'objets cosmétiques pour les armes et les opératifs.",
		ja = "武器とオペレーター用のコスメティックアイテムを購入するメニューを開きます。",
		ko = "무기와 요원용 외형 아이템을 구매하는 메뉴를 엽니다.",
		it = "Apre il menu per l'acquisto di oggetti cosmetici per armi e operatori.",
		pl = "Otwiera menu zakupu przedmiotów kosmetycznych dla broni i agentów.",
		es = "Abre el menú para comprar artículos cosméticos para armas y operativos.",
 ["pt-br"] = "Abre o menu para comprar itens cosméticos para armas e operativos.",
	},

	-- Penance
	open_penance_view_key = {
		en = "Shrine Penitentax",
		ru = "Святилище Искуплений",
 ["zh-cn"] = "神龛忏悔者",
 ["zh-tw"] = "神龕懺悔者",
		de = "Schrein der Buße",
		fr = "Autel pénitentiel",
		ja = "苦行の神殿",
		ko = "참회 신전",
		it = "Santuario penitenziale",
		pl = "Sanktuarium pokuty",
		es = "Santuario penitencial",
 ["pt-br"] = "Santuário penitencial",
	},
	open_penance_view_key_description = {
		en = "Opens the Penance view.",
		ru = "Открывает меню искуплений.",
 ["zh-cn"] = "打开苦修界面。",
 ["zh-tw"] = "打開苦修介面。",
		de = "Öffnet die Bußansicht.",
		fr = "Ouvre la vue des pénitences.",
		ja = "ペナンスビューを開きます。",
		ko = "참회 화면을 엽니다.",
		it = "Apre la vista delle penitenze.",
		pl = "Otwiera widok pokut.",
		es = "Abre la vista de penitencias.",
 ["pt-br"] = "Abre a visualização de penitências.",
	},

	-- Havoc Mode
	open_havoc_background_view_key = {
		en = "Havoc Mode",
		ru = "Режим Хавок",
 ["zh-cn"] = "Havoc Mode",
 ["zh-tw"] = "Havoc 模式",
		de = "Havoc-Modus",
		fr = "Mode Havoc",
		ja = "ハボックモード",
		ko = "하복 모드",
		it = "Modalità Flagello",
		pl = "Tryb Havoc",
		es = "Modo Havoc",
 ["pt-br"] = "Modo Havoc",
	},
	open_havoc_background_view_key_description = {
		en = "Opens the Havoc Menu.",
		ru = "Открывает меню режима Хавок.",
 ["zh-cn"] = "打开 Havoc 菜单。",
 ["zh-tw"] = "打開 Havoc 選單。",
		de = "Öffnet das Havoc-Menü.",
		fr = "Ouvre le menu Havoc.",
		ja = "ハボックメニューを開きます。",
		ko = "하복 메뉴를 엽니다.",
		it = "Apre il menu Flagello.",
		pl = "Otwiera menu Havoc.",
		es = "Abre el menú Havoc.",
 ["pt-br"] = "Abre o menu Havoc.",
	},

	-- Expedition Mode
	open_expedition_view_key = {
		en = "Expedition Mode",
		ru = "Режим Экспедиции",
 ["zh-cn"] = "Expedition Mode",
 ["zh-tw"] = "Expedition 模式",
		de = "Expeditions-Modus",
		fr = "Mode Expédition",
		ja = "遠征モード",
		ko = "원정 모드",
		it = "Modalità Spedizione",
		pl = "Tryb Ekspedycji",
		es = "Modo Expedición",
 ["pt-br"] = "Modo Expedição",
	},
	open_expedition_view_key_description = {
		en = "Opens the Expedition Menu.",
		ru = "Открывает меню Экспедиций.",
 ["zh-cn"] = "打开 Expedition 菜单。",
 ["zh-tw"] = "打開 Expedition 選單。",
		de = "Öffnet das Expeditions-Menü.",
		fr = "Ouvre le menu Expédition.",
		ja = "遠征メニューを開きます。",
		ko = "원정 메뉴를 엽니다.",
		it = "Apre il menu Spedizione.",
		pl = "Otwiera menu Ekspedycji.",
		es = "Abre el menú Expedición.",
 ["pt-br"] = "Abre o menu Expedição.",
	},
}
